### ISSUE TITLE
XPermit: change the "User" to username and same in other tabs

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#11]
in the detail view of a user on top there is User that has to be changed with the First name and last name of the select user and same pattern has to be applied everywhere

**Comment by Swapnilkumbhar31** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/f0db75ce9087142d5c880885cc518db72be98de6](https://github.com/exadatum/xstudio/commit/f0db75ce9087142d5c880885cc518db72be98de6)
