### ISSUE TITLE
XPermit: remove status on unnecessary places

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#13]
status column is used at so many places. remove it and use some other columns

**Comment by Swapnilkumbhar31** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/3b09050a4ef794c57d15574734052ffcf5be6516](https://github.com/exadatum/xstudio/commit/3b09050a4ef794c57d15574734052ffcf5be6516)
