### ISSUE TITLE
use plain editor for json editing

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#19]
use plain editor for json editing.
in edit mode use plain editor but in case of view mode use the existing plugin because it provides search and other feature.
try to remove the "powered by ace" from the plugin if possible

**Comment by Swapnilkumbhar31** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/fc3a26bdcc390511ad8f5b091a714348859d31d0](https://github.com/exadatum/xstudio/commit/fc3a26bdcc390511ad8f5b091a714348859d31d0)
