### ISSUE TITLE
XPermit:put pagination down in audit log

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#21]
put pagination down in audit log

**Comment by Swapnilkumbhar31** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/3e0678a49ab08653a03cdf927e5e2ecd592f3a53](https://github.com/exadatum/xstudio/commit/3e0678a49ab08653a03cdf927e5e2ecd592f3a53)

**Comment by xsachingupta** [comment]
you changed the color also ?

**Comment by Swapnilkumbhar31** [comment]
#7 This issue will be solved soon.
