### ISSUE TITLE
XPermit:provision for editing a service

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#25]
As of now there is no provision for editing a service and its associated policies
As we are bringing in the clone feature in service and also integration of State in service so now we have to provide a way to edit services.
this might be using a wizard or some other approach

**Comment by xsachingupta** [comment]
@Swapnilkumbhar31 lets discuss

**Comment by Swapnilkumbhar31** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/fc3a26bdcc390511ad8f5b091a714348859d31d0](https://github.com/exadatum/xstudio/commit/fc3a26bdcc390511ad8f5b091a714348859d31d0)
