### ISSUE TITLE
XPermit: Use images or image icon if image is not there in the users tab

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#29]
Use images or image icon if image is not there in the users tab

**Comment by Swapnilkumbhar31** [comment]
Resovled
[https://github.com/exadatum/xstudio/commit/b3066eaa5720ef9a5496ea5724d66590ee8b5cae](https://github.com/exadatum/xstudio/commit/b3066eaa5720ef9a5496ea5724d66590ee8b5cae)
