### ISSUE TITLE
XConfig: icons getting misplaced on hover on group in graph

### ISSUE THREAD

**Issue by xsachingupta** [exadatum/xstudio#3]
icons are getting misplaced on mouse hover on group in graph

**Comment by xsachingupta** [comment]
@suniljadhav01 what is the status on this ?

**Comment by suniljadhav01** [comment]
Resolved
[https://github.com/exadatum/xstudio/commit/bd151a6e54e1f32e3780aed795c2a9be4091be24](https://github.com/exadatum/xstudio/commit/bd151a6e54e1f32e3780aed795c2a9be4091be24)
